spring:
  application:
    name: discovery-service

server:
  port: 8010

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 0

logging:
  level:
    com.netflix: 'WARN'
    org.springframework.cloud: 'WARN'